### ISSUE TITLE
Splitting a polygon with a polyline that crosses the polygon multiple times sometimes does not work

### ISSUE THREAD

**Issue by timrutter** [rowanwins/polygon-splitter#3] opened 2021-07-07 08:02 UTC
me again, I thought i'd create this one a separate issue as its not to do with holes.  If I split this polygon:
`{"type":"Polygon","coordinates":[[[0,0],[10,0],[10,10],[0,10],[0,0]]]}`

with this polyline:
`{"type":"LineString","coordinates":[[-2.5,5],[5,12.5],[12.5,5],[5,-2.5]]}`

the output is this, the third polygon it returns is not correct
`{"type":"Feature","properties":{},"geometry":{"type":"MultiPolygon","coordinates":[[[[0,6.011473509933775],[0,0],[6.015058430717863,0],[10,3.965083056478406],[10,5.998302828618968],[5.991633333333334,10],[4.021819699499164,10],[0,6.011473509933775]],[[6.015058430717863,0],[10,0],[10,3.965083056478406],[6.015058430717863,0]],[[10,3.965083056478406],[10,5.998302828618968],[5.991633333333334,10],[4.021819699499164,10],[0,6.011473509933775],[0,0],[6.015058430717863,0],[10,3.965083056478406]],[[10,5.998302828618968],[10,10],[5.991633333333334,10],[10,5.998302828618968]]]]}}`

I could consider restricting that use case as its probably a bit complex for my needs in reality.  I have to say though I'm finding it very easy to find cases where it returns incorrect results.  If you like I can share some more

**Comment by rowanwins** [comment] 2021-07-07 08:42
> I have to say though I'm finding it very easy to find cases where it returns incorrect results. If you like I can share some more

Welcome to the joy of writing geometry algorithms when no-one is paying you to do so (even though there is a sponsor button on the repo) ;)
On a more serious note this is still v0.0.1, it hasn't been battle tested, so failing cases do help.

In this case it looks like the 3rd contour is a duplicate of the 1st (albiet with the coords in different order). I suspect at some stage the rewiring of the polygons is taking a wrong turn and so it's collecting the wrong output contour.

**Comment by timrutter** [comment] 2021-07-07 08:48
sorry I didn't meant to sound overly critical.  I'm happy to share more examples if they are helpful.  I'll add them as new issues

**Comment by rowanwins** [comment] 2021-07-08 01:41
No worries @timrutter :)

I've just published 0.0.2 which fixes a bunch of issues including this issue (not the single segment issue of #2 yet) but I'd be keen for you to test it out.

Turns out setting the fill-opacity of polygons to something greater than 0 helps to spot the dodgy overlapping polygons because if there are overlapping polys they become transparent because of svg rendering rules.

**Closed** 2021-07-20 03:07 UTC
