### ISSUE TITLE
Bug with handling for lines with only a single segment when encountering holes

### ISSUE THREAD

**Issue by timrutter** [rowanwins/polygon-splitter#2] opened 2021-07-07 07:11 UTC
Holes are defined in geojson as clockwise linestrings.  If i create a simple square with a square hole in the centre i.e. a Polygon with 2 rings one anticlockwise boundary and one clockwise hole and split the polygon with a polyline that doesn't cross the hole but does cross the boundary, it returns an array of two polygons and the hole has disappeared.

If i then try again and split the polygon so that the polyline goes across the middle of the hole, it throws an exception.  Cannot read property 'p' of undefined

I know you are using a method where you walk around the perimeter but I can't see how this will work with holes.

**Comment by rowanwins** [comment] 2021-07-07 07:14
Can you share your geojson that you're using?

**Comment by timrutter** [comment] 2021-07-07 07:21
Polygon:
`{  "type":"Polygon", "coordinates":[[[0,0],[10,0],[10,10],[0,10],[0,0]],[[2.5,2.5],[2.5,7.5],[7.5,7.5],[7.5,2.5],[2.5,2.5]]]}`

Polyline:
{"type":"LineString","coordinates":[[5,11],[5,-1]]}

hopefully I'm doing something wrong :)

**Comment by rowanwins** [comment] 2021-07-07 07:33
Hi @timrutter 

I've managed to replicate. The issue is because the line only has two points, I added a midpoint and it works fine
![debug 2021-07-07 17-31-46](https://user-images.githubusercontent.com/6735870/124718238-3d5c5500-df49-11eb-9efc-a8e52ed9bc56.png)
I'll need to work out how to handle those lines with only a single segment.

**Comment by rowanwins** [comment] 2021-07-07 07:37
The problem only occurs when there is a hole in the polygon

**Comment by timrutter** [comment] 2021-07-07 07:47
yes I can confirm putting a mid point in works.  thanks for the rapid response to this by the way :)  

There is the other case as well though and this isn't fixed with a mid point:

Polygon (same as above):
`{ "type":"Polygon", "coordinates":[[[0,0],[10,0],[10,10],[0,10],[0,0]],[[2.5,2.5],[2.5,7.5],[7.5,7.5],[7.5,2.5],[2.5,2.5]]]}`

Polyline (slighty to the right so it doesn't cut the hol:
`{"type":"LineString","coordinates":[[8.5,11],[8.5,-1]]}`

in this case the polygon is cut correctly but the hole disappears, I'll check I'm interpreting the result correctly in my code

**Comment by rowanwins** [comment] 2021-07-20 04:12
Fixed in v0.3

**Closed by rowanwins** 2021-07-20 04:12 UTC
